
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvesqulwpnleyhshgxgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZXNxdWx3cG5sZXloc2hneGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODMyNTQsImV4cCI6MjA2MTY1OTI1NH0.-I-eTPXxILhZCLKxd-YNFpKxmh8_cTdTTJS2Ucp5TIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
